// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHPzNw05zKj5gIxChK5HEN3E1d-U6iTSc',
    appId: '1:201995140504:web:363252f15843a579daffed',
    messagingSenderId: '201995140504',
    projectId: 'flutter-app-24779',
    authDomain: 'flutter-app-24779.firebaseapp.com',
    storageBucket: 'flutter-app-24779.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAECOs_zjs2a06KsWzuMWaJej5cMjcaoec',
    appId: '1:201995140504:android:9db1fe8c37ebb3c2daffed',
    messagingSenderId: '201995140504',
    projectId: 'flutter-app-24779',
    storageBucket: 'flutter-app-24779.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD6p0HdYuUNDtOhNzIwziq2r7i0fNU_cI',
    appId: '1:201995140504:ios:e717a0c720654347daffed',
    messagingSenderId: '201995140504',
    projectId: 'flutter-app-24779',
    storageBucket: 'flutter-app-24779.appspot.com',
    androidClientId: '201995140504-8t4ibnhfc24rvjk8isinnjsdqbvcbsee.apps.googleusercontent.com',
    iosClientId: '201995140504-oq8625umchcrj64smlpijmttaonsf679.apps.googleusercontent.com',
    iosBundleId: 'com.example.easaccTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD6p0HdYuUNDtOhNzIwziq2r7i0fNU_cI',
    appId: '1:201995140504:ios:4722f81f6166a4aadaffed',
    messagingSenderId: '201995140504',
    projectId: 'flutter-app-24779',
    storageBucket: 'flutter-app-24779.appspot.com',
    androidClientId: '201995140504-8t4ibnhfc24rvjk8isinnjsdqbvcbsee.apps.googleusercontent.com',
    iosClientId: '201995140504-bv9buvchsk5hiffcnitlocmcf6uo4j1c.apps.googleusercontent.com',
    iosBundleId: 'com.example.easaccTask.RunnerTests',
  );
}
